# Generated by Django 3.1.13 on 2021-11-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20210906_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ml_params',
            field=models.JSONField(default=dict, help_text='Machine learning training params', null=True, verbose_name='ml params'),
        ),
    ]
