# Generated by Django 3.1.13 on 2021-11-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_project_ml_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ml_arguments',
            field=models.JSONField(default=[], help_text='Machine learning training data arguments', null=True, verbose_name='ml arguments'),
        ),
    ]
