# Generated by Django 3.1.13 on 2021-11-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_ml_arguments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='ml_arguments',
        ),
        migrations.AddField(
            model_name='project',
            name='ml_augments',
            field=models.JSONField(default=list, help_text='Machine learning training data arguments', null=True, verbose_name='ml arguments'),
        ),
    ]
